---

classes:
    - metacpan::role::production
    - metacpan::system::mongodb

exim::config_type: 'satellite'
exim::smarthost: 'smtp.mailgun.org'
exim::relayhost: '*.mailgun.org'

metacpan::carton_args: '--deployment --without develop'

metacpan::elasticsearch::status: 'disabled'
metacpan::elasticsearch::memory: '10g'

# Let's have rrr on all machines for now
# we can setup cpan.mc.org with a failover!
metacpan::rrrclient::enable: true

metacpan::system::ramdisks:
    '/mnt/scratch_disk':
        size: '1G'
        valid_mins: '45'

metacpan::crons::general:
    metacpan_clean_up_source:
      ensure : present
    run_puppet:
      ensure : present

metacpan::web::starman:

  metacpan-api:
    git_enable: true
    starman_workers: 30

metacpan::web::static:
  metacpan-explorer:
    git_enable: true

metacpan::users:
    leo:
        admin    : true
        fullname : "Leo Lapworth <leo@cuckoo.org>"
        no_passwd_sudo : true
    rhodri:
        admin    : true
        fullname : "Rhodri Metcalfe-Davies <rhodrimd@digitalcraftsmen.com>"
        no_passwd_sudo : true
    olaf:
        admin    : true
        fullname : "Olaf Alders <olaf.alders@gmail.com>"
        no_passwd_sudo : true
    ssoriche:
        admin    : true
        fullname : 'Shawn Sorichetti <shawn@coloredblocks.com>'
        shell    : /bin/zsh
    rwstauner:
        admin    : true
        fullname : 'Randy Stauner <rwstauner@cpan.org>'
        shell    : /bin/zsh
    sawyer:
        ensure   : absent
        admin    : true
        fullname : 'Sawyer <xsawyerx@cpan.org>'
        shell    : /bin/zsh
    trs:
        admin    : true
        fullname : "Thomas Sibley <tsibley@cpan.org>"
    matthewt:
        admin    : true
        fullname : "Matt S Trout <perl-stuff@trout.me.uk>"
    haarg:
        admin    : true
        fullname : "Graham Knop <haarg@haarg.org>"
    mhorsfall:
        admin    : true
        fullname : "Matthew Horsfall (alh) <wolfsage@gmail.com>"
    ben:
        ensure   : absent
        admin    : true
        fullname : "Ben Hundley <ben@qbox.io>"
    ether:
        admin    : true
        fullname : "Karen Etheridge <ether@cpan.org"
    mickey:
        admin    : true
        fullname : "Mickey Nasriachi <mickey@cpan.org>"
        no_passwd_sudo : true
    # David Cantrell needs access for cpxxxan and cpan deps (rsync)
    davidc:
        fullname : "David Cantrell <david@cantrell.org.uk>"
    brad:
        admin    : true
        fullname : "Brad Lhotsky <brad.lhotsky@gmail.com>"
    jberger:
        admin    : true
        fullname : "Joel Berger <joel.a.berger@gmail.com>"
    mohawk2:
        admin    : true
        fullname : "Ed J <etj@cpan.org>"
    abraxxa:
        admin    : true
        fullname : "Alexander Hartmaier <abraxxa@cpan.org>"
        no_passwd_sudo : true

