#!/bin/sh
# -*- sh -*-

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "config" ]; then

	echo 'graph_title ElasticSearch open files'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel number of open files'
	echo 'graph_category system'
	echo 'used.label open files'
	echo 'used.type GAUGE'
	echo 'used.info The number of currently open files.'
	echo 'max.label max open files'
	echo 'max.type GAUGE'
	exit 0
fi


# while true; do su -c 'ls /proc/$(pidof whatever)/fd' elasticsearch |wc -l |nc  -l -q0 localhost 9998; done 

PID=`ps -u elasticsearch -opid,comm | grep java | awk '{ print $1 }'`
VALUE=`ls /proc/$PID/fd/ | wc | awk '{ print $1 }'`
echo "used.value $VALUE"
echo "max.value 65000"
